name: presentation_master_2
description: All-in-one presentation remote and note taking app

publish_to: 'none'

version: 3.2.2+53

environment:
  sdk: '>=2.19.2 <4.0.0'




# TODO: Reorder 
dependencies:
  flutter:
    sdk: flutter

  logger: ^1.1.0

  shared_preferences: ^2.1.1

  wakelock_plus: ^1.1.1
  flutter_vibrate: ^1.3.0

  http: ^1.1.0
  network_info_plus: ^4.0.1
  ping_discover_network_forked: ^0.0.1
  regexed_validator: ^2.0.0+1
  url_launcher: ^6.0.18
  in_app_review: ^2.0.6
  in_app_purchase: ^3.1.8

  flutter_native_splash: ^2.2.0

  google_fonts: ^5.1.0
  flutter_markdown: ^0.6.10+2
  zwidget: ^0.0.2
  overlay_tooltip: ^0.2.3
  skeletons: ^0.0.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.13.1
  rename: ^2.1.1





flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/launcher_icon.png"

flutter:
  uses-material-design: true
  # TODO: R unused assets
  fonts:
    - family: Trap
      fonts:
        - asset: assets/fonts/Trap_V1.1/Trap-Regular.otf
        - asset: assets/fonts/Trap_V1.1/Trap-Light.otf
          weight: 100
        - asset: assets/fonts/Trap_V1.1/Trap-Light.otf
          weight: 200
        - asset: assets/fonts/Trap_V1.1/Trap-Light.otf
          weight: 300
        - asset: assets/fonts/Trap_V1.1/Trap-Regular.otf
          weight: 400
        - asset: assets/fonts/Trap_V1.1/Trap-Medium.otf
          weight: 500
        - asset: assets/fonts/Trap_V1.1/Trap-Bold.otf
          weight: 600
        - asset: assets/fonts/Trap_V1.1/Trap-Bold.otf
          weight: 700
        - asset: assets/fonts/Trap_V1.1/Trap-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Trap_V1.1/Trap-Black.otf
          weight: 900




flutter_native_splash:
  color: "#000000"
  image: assets/images/splash_screen_icon.png
  android_12:
    color: "#000000"
    image: assets/images/splash_screen_icon.png